services:

  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  go-backend:
    build:
      context: .
      dockerfile: ./go-backend/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydb?sslmode=disable
    ports:
      - "8080:8080"
      - "10000-10100:10000-10100/udp"
    volumes:
      - backend:/deploy/go-backend/files

  inference-backend:
    image: inference-backend:latest
    build:
      context: .
      dockerfile: ./inference-backend/Dockerfile
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - backend:/deploy/inference-backend/files

volumes:
  backend:
  pgdata:
