services:

  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - backend-network
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/mydb?sslmode=disable
    ports:
      - "8080:8080"
      - "10000-10100:10000-10100/udp"
    networks:
      - backend-network
    volumes:
      - backend:/deploy/server/files

  inference:
    image: inference:latest
    build:
      context: .
      dockerfile: ./inference/Dockerfile
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    networks:
      - backend-network
    volumes:
      - backend:/deploy/inference/files

volumes:
  backend:
  pgdata:

networks:
  backend-network:
    driver: bridge